

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(23) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar(23) UNIQUE NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(23) UNIQUE NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "email" varchar(35) UNIQUE NOT NULL,
  "password" varchar(15) NOT NULL,
  "age" int
);

CREATE TABLE "users_role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firts_name" int NOT NULL,
  "role" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "description" varchar(60) NOT NULL,
  "level" int NOT NULL,
  "teacher" int NOT NULL,
  "category" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" int NOT NULL,
  "url" varchar(100) NOT NULL
);

ALTER TABLE "users_role" ADD FOREIGN KEY ("firts_name") REFERENCES "users" ("id");

ALTER TABLE "users_role" ADD FOREIGN KEY ("role") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "levels" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("title") REFERENCES "courses" ("id");

sunny_entregable=# \dt
           Listado de relaciones
 Esquema |    Nombre    | Tipo  |  Due±o
---------+--------------+-------+----------
 public  | categories   | tabla | postgres
 public  | course_video | tabla | postgres
 public  | courses      | tabla | postgres
 public  | levels       | tabla | postgres
 public  | roles        | tabla | postgres
 public  | users        | tabla | postgres
 public  | users_role   | tabla | postgres
(7 filas)

sunny_entregable=# SELECT * fROM categories;
sunny_entregable=# SELECT * fROM course_video;
sunny_entregable=# SELECT * fROM courses;
sunny_entregable=# SELECT * fROM levels;
sunny_entregable=# SELECT * fROM roles;
sunny_entregable=# SELECT * fROM users;
sunny_entregable=# SELECT * fROM users_role;

